---
galaxy_info:
  role_name: yangsuite_docker
  author: Igor Manassypov
  description: Deploy Cisco YANG Suite via upstream Docker Compose
  license: MIT
  min_ansible_version: "2.14"
dependencies: []
