[launcher]
author = Network Operations
description = BGP EVPN VXLAN Fabric Operational Health — Cisco Catalyst Campus
version = 1.5.0

[app]
build = 106
version = 1.5.0

[package]
id = campus_evpn_assurance
check_for_updates = false

[ui]
is_visible = true
label = Campus EVPN Assurance

[install]
state = enabled
